on:
  push:
    workflow_dispatch:
    branches:
      - 'ci/develop'
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/macos-reusable.yml@develop
    with:
      runTests: false
      package-name: febio-studio
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "ci/develop",
          "version": "v4.5",
        }
    secrets: inherit
